runtime: python311
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  SECRET_KEY: "change-me-in-prod"
  # For demo purposes on App Engine Standard, use a writable SQLite DB in /tmp.
  # For production or extra credit, point this to a Cloud SQL database URL.
  DATABASE_URL: "sqlite:////tmp/app.db"

handlers:
  - url: /static
    static_dir: static
  - url: /favicon.ico
    static_files: static/favicon.ico
    upload: static/favicon.ico
  - url: /.*
    script: auto
